Zondax/rosetta-filecoin-proxy

- .circleci/config.yml
- main.go
- rosetta/services/account.go
- rosetta/services/account_test.go
- rosetta/services/block.go
- rosetta/services/block_test.go
- rosetta/services/construction.go
- rosetta/services/construction_test.go
- rosetta/services/errors.go
- rosetta/services/helpers.go
- rosetta/services/helpers_test.go
- rosetta/services/mempool.go
- rosetta/services/mempool_test.go
- rosetta/services/mocks/fullnode_mock.go
- rosetta/services/network.go
- rosetta/services/network_test.go
- rosetta/services/sync_status.go
- rosetta/services/sync_status_test.go
- rosetta/tests/rosetta_test.go
- Some code clean up from services files
- Add rosetta rpc server start&retry sequences
- Add minimal endpoint test using rosetta-sdk client
- Add mock of Lotus api for unit testing
> Rosetta rpc server

- Makefile
- main.go
- rosetta/services/constants.go
Inject the variables :
```
RosettaSDKVersion
LotusVersion      
GitRevision     
```
> Inject versions info at build time

- rosetta/examples/create_transaction.go
- rosetta/services/construction.go
- rosetta/tests/rosetta_cli_test.sh
- rosetta/tests/rosetta_test.go
- Switch metadata keys to camel case
- Fixing rosetta-cli version
- Set address as optional parameter
> Bug fix release

- go.mod
- go.sum
- rosetta/tests/rosetta-config.txt
- rosetta/tests/rosetta_cli_test.sh
Closes https://github.com/Zondax/rosetta-filecoin-proxy/issues/36
> Upgrade versions of rosetta-sdk & rosetta-cli

- rosetta/services/block.go
> Add detect null TipSets

- rosetta/tests/rosetta-config.txt
- rosetta/tests/rosetta_cli_test.sh
- start.sh
- start.sh: wait for token to exist before setting env
- update tests to use rosetta-cli v0.5.2
> Minor fixes and updates

- rosetta/services/sync_status.go
- Add check for nil pointer before querying a sync worker
> Fix sync_status

- main.go
- rosetta/services/block.go
- rosetta/services/constants.go
- rosetta/services/errors.go
- rosetta/services/helpers.go
- rosetta/services/network.go
- rosetta/tests/rosetta-config.json
- rosetta/tests/rosetta_cli_test.sh
- Use Lotus's `StateCompute` to build transactions/operations [**Beta**]
- Upgrade rosetta-cli to v0.5.7
- Fix asserter to accept historical balance lookup
- Minor code cleanup
> Traces support

- rosetta/services/account.go
- rosetta/services/block.go
- rosetta/services/helpers.go
- rosetta/services/mempool.go
- `StateCompute`: fix tipset argument (Closes #66 )
- Fix "Fee" operations being related to previous ones (Closes  #77 )
- Add SwapSigner operation with `msg.to` (Closes #68 )
> Traces_Fixes

- rosetta/services/block.go
- rosetta/services/construction.go
- rosetta/services/helpers.go
- rosetta/tests/rosetta_test.go
- Closes #87 
- Closes #95
- Fix attempt for #93
> Adjust metadata endpoint

- go.mod
- go.sum
- rosetta/services/block.go
- Upgrade to Lotus 0.10.2
- Fix related operations (closes #102 )
> Upgrades&bugfix

- go.mod
- go.sum
- rosetta/services/block.go
- Upgrade to lotus 0.10.3-pre1
- Use `TotalCost` from trace data for `Fee` operation (closes #101 )
> Fix Fee operation

- .circleci/config.yml
- .github/workflows/main.yml
- Makefile
- main.go
- rosetta/services/constants.go
- rosetta/tests/rosetta-config-PR.json
- rosetta/tests/rosetta-config-push.json
- rosetta/tests/rosetta_cli_test_PR.sh
- rosetta/tests/rosetta_cli_test_push.sh
- rosetta/tests/rosetta_test.go
Finish configuration for github actions using self hosted runners
> Remote test runner

- .github/workflows/main.yml
- README.md
- rosetta/services/construction.go
- rosetta/tests/rosetta-config-PR.json
- rosetta/tests/rosetta-config-push.json
- rosetta/tests/rosetta_cli_test_PR.sh
- rosetta/tests/rosetta_cli_test_push.sh
- rosetta/tests/rosetta_test.go
- Add option to pass `value` (string) on `ConstructionMetadataRequest.Options` for better gas estimations
- Upgrade rosetta-cli to `v0.5.14`
- Tweak configs for maximum hardware performance 
- Add github actions badge to readme
> CI config improvements & fixes

- go.mod
- go.sum
- rosetta/services/block.go
- rosetta/services/helpers.go
- rosetta/services/mocks/fullnode_mock.go
- rosetta/services/network.go
- rosetta/services/sync_status.go
- rosetta/services/sync_status_test.go
- rosetta/tests/rosetta-config-PR.json
- Update `lotus` to v1.7.0-rc1
- Update `rosetta-filecoin-lib` to v1.700.0
- Use V4 actors
- Improve Exec params inspection. Closes #136
> Lotus v1.7.0-rc1 

- go.mod
- go.sum
- rosetta/services/mocks/fullnode_mock.go
- rosetta/tests/rosetta-config-PR.json
- Update `lotus` to v1.8.0
- Update `rosetta-filecoin-lib` to v1.800.1
> Support for lotus v1.8.0

- go.mod
- go.sum
- rosetta/services/mocks/fullnode_mock.go
:link: [zboto Link](https://app.clickup.com/t/2n9vrb6)
> Update/lotus v1.16.0 

- go.mod
- go.sum
:link: [zboto Link](https://app.clickup.com/t/2gp0n7p)
> Bump rosetta-filecoin-lib

- rosetta/services/block.go
:link: [zboto Link](https://app.clickup.com/t/2hjhyt5)
> Fix msig params parse

- .github/workflows/main.yml
- Makefile
- rosetta/services/block.go
- rosetta/services/constants.go
- rosetta/tests/rosetta-config-PR-mainnet.json
- Add support for multisig methods `Approve` and `Cancel`
- Only process subcalls of successfully executed parent transactions
:link: [zboto Link](https://app.clickup.com/t/2wu2k4u)
> Add support for multisig Approve and Cancel methods

- go.mod
- go.sum
:link: [zboto Link](https://app.clickup.com/t/36gv1ju)
> Bumped Lotus to v1.18

- rosetta/services/mocks/fullnode_mock.go
:link: [zboto Link](https://app.clickup.com/t/36w9y4x)
> Implemented FullNode mocks

- go.mod
- go.sum
- rosetta/services/construction.go
- rosetta/services/helpers.go
:link: [zboto Link](https://app.clickup.com/t/8677h4uzt)
> fix: support send to f4 addresses

- go.mod
- go.sum
- rosetta/services/block.go
- rosetta/services/constants.go
:link: [zboto Link](https://app.clickup.com/t/862jdkjgq)
> Support deposits from actors

- .github/workflows/main.yml
- go.mod
- go.sum
- rosetta/tests/rosetta-config-PR-calibration.json
:link: [zboto Link](https://app.clickup.com/t/86931hvdq)
> Bump lotus version to v1.24.0-rc4

- go.mod
- go.sum
- rosetta/tests/rosetta-config-PR-calibration.json
:link: [zboto Link](https://app.clickup.com/t/869358xr4)
> Bump lotus to v1.24.0-rc6

- go.mod
- go.sum
- rosetta/tests/rosetta-config-PR-calibration.json
:link: [zboto Link](https://app.clickup.com/t/869ah7fja)
> Support lotus v1.34.1
